# Generated by Django 5.0.1 on 2024-01-20 21:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='user@email.com', max_length=254)),
                ('q_posts', models.BigIntegerField(default=0)),
                ('q_followers', models.BigIntegerField(default=0)),
                ('q_following', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('likes', models.BigIntegerField(default=0)),
                ('date_post', models.DateField(verbose_name=datetime.datetime(2024, 1, 20, 21, 21, 24, 161829, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
