# Generated by Django 5.0.1 on 2024-01-20 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateField(verbose_name=datetime.datetime(2024, 1, 20, 23, 8, 14, 126495, tzinfo=datetime.timezone.utc)),
        ),
    ]
