# Generated by Django 5.0.1 on 2024-01-21 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_post_date_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locate',
            field=models.CharField(default='Coxim, Mato Grosso do Sul, Brasil', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.URLField(default='https://cdn.vuetifyjs.com/images/cards/docks.jpg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateField(verbose_name=datetime.datetime(2024, 1, 21, 2, 23, 33, 437403, tzinfo=datetime.timezone.utc)),
        ),
    ]
