# Generated by Django 5.0.1 on 2024-01-21 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_locate_post_media_alter_post_date_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='midia',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateField(verbose_name=datetime.datetime(2024, 1, 21, 2, 24, 44, 127916, tzinfo=datetime.timezone.utc)),
        ),
    ]
